-- AlterTable
ALTER TABLE "Cita" ADD COLUMN IF NOT EXISTS "montoAdelanto" DECIMAL(10, 2) NOT NULL DEFAULT 20.00;
ALTER TABLE "Cita" ADD COLUMN IF NOT EXISTS "comprobanteUrl" TEXT;
ALTER TABLE "Cita" ADD COLUMN IF NOT EXISTS "metodoPagoReserva" TEXT;